[package]
name = "honcho-rust"
version = "0.1.0"
authors = ["Tim Morgan <tim@timmorgan.org>"]

[dependencies]
clap = "2.11.0"
nix = "0.8.0"
redis = "0.7.0"
yaml-rust = "0.3.3"
cmdline_words_parser = "0.0.2"
